Qhana
UST-QuAntiL/quantil-docker pull request #34
Opened 2022-09-23 12:31 UTC by cloudsftp

Add containers for QHana.

2022-09-26 12:57 UTC, salmma requested changes
File q can be removed? 
See other comments

2022-09-26 12:57 UTC, salmma commented on README.md
> +- `QHana`
First a --> A, adapt everywhere

2022-09-26 12:57 UTC, salmma commented on README.md
> +| Redis (QHana)               | <http://localhost:6379>               | [Link](https://github.com/redis/redis)                     | [Link](https://hub.docker.com/_/redis)
Isn't it possible to use the same Redis?

2022-09-26 12:57 UTC, salmma commented on README.md
> +| QHAna Plugin Runner         |<http://localhost:5006>                | [Link](https://github.com/UST-QuAntiL/qhana-plugin-runner) | [Link](https://github.com/UST-QuAntiL/qhana-plugin-runner/pkgs/con
again, is is required to use several plugin runners?

2022-09-26 12:57 UTC, salmma commented on README.md
> +| NISQ-Analyzer-UI            | <http://localhost:4201>               | [Link](https://github.com/UST-QuAntiL/nisq-analyzer-ui)       | [Link](https://github.com/UST-QuAntiL/qhana-ui/pkgs/container/q
please place the NISQ-Analyzer-UI under the NISQ Analyzer component, and use port 5009

2022-09-26 12:57 UTC, salmma commented on README.md
> +* `4200`
avoid standard ports instead group related components together, eg 5000< QHAna ports < 5009

2022-09-26 12:57 UTC, salmma commented on docker-compose.yml
> +  nisq-analyzer-ui:
also here place nisq analyzer ui next to the nisq analyzer

2022-09-26 12:59 UTC, salmma requested changes

2022-09-26 12:59 UTC, salmma commented on docker-compose.yml
> +    profiles: ["all", "nisqAnalyzer", "nisqAnalyzerCompilerComparison", "QHana"]
let the profile lower case --> qhana

2022-10-04 08:21 UTC, salmma approved these changes
LGTM

2022-10-04 09:19 UTC, buehlefs requested changes

2022-10-04 09:19 UTC, buehlefs commented on README.md
> +| Redis (QHana)               | <http://localhost:6379>               | [Link](https://github.com/redis/redis)                     | [Link](https://hub.docker.com/_/redis)
Remove this redis line

2022-10-04 09:19 UTC, buehlefs commented on README.md
> +| QHAna Plugin Runner (Prio)  |<http://localhost:5005>                | [Link](https://github.com/UST-QuAntiL/qhana-plugin-runner) | [Link](https://github.com/UST-QuAntiL/qhana-plugin-runner/pkgs/con
There is no longer a separate plugin runner/worker. Please adapt readme to reflect changes.

2022-10-05 09:26 UTC, buehlefs approved these changes

2022-10-05 15:17 UTC, merged